//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/nodeSensor/GenericPacket.msg.
//

#ifndef _GENERICPACKET_M_H_
#define _GENERICPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
 
#include "ApplicationPacket_m.h" 
// }}

/**
 * Struct generated from src/node/application/nodeSensor/GenericPacket.msg:26 by nedtool.
 */
struct packetInfo
{
    packetInfo();
    unsigned short OriginNodeID;
    int messageType;
};

void doPacking(cCommBuffer *b, packetInfo& a);
void doUnpacking(cCommBuffer *b, packetInfo& a);

/**
 * Class generated from <tt>src/node/application/nodeSensor/GenericPacket.msg:30</tt> by nedtool.
 * <pre>
 * packet GenericPacket extends ApplicationPacket
 * {
 *     packetInfo extraData;
 * }
 * </pre>
 */
class GenericPacket : public ::ApplicationPacket
{
  protected:
    packetInfo extraData_var;

  private:
    void copy(const GenericPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GenericPacket&);

  public:
    GenericPacket(const char *name=NULL, int kind=0);
    GenericPacket(const GenericPacket& other);
    virtual ~GenericPacket();
    GenericPacket& operator=(const GenericPacket& other);
    virtual GenericPacket *dup() const {return new GenericPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual packetInfo& getExtraData();
    virtual const packetInfo& getExtraData() const {return const_cast<GenericPacket*>(this)->getExtraData();}
    virtual void setExtraData(const packetInfo& extraData);
};

inline void doPacking(cCommBuffer *b, GenericPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GenericPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GENERICPACKET_M_H_

