//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/nodeSensor/SnToIotPacket.msg.
//

#ifndef _SNTOIOTPACKET_M_H_
#define _SNTOIOTPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
 
#include "ApplicationPacket_m.h" 
// }}

/**
 * Struct generated from src/node/application/nodeSensor/SnToIotPacket.msg:26 by nedtool.
 */
struct snInfo
{
    snInfo();
    unsigned short nodeID;
    double locX;
    double locY;
    double spentEnergy;
};

void doPacking(cCommBuffer *b, snInfo& a);
void doUnpacking(cCommBuffer *b, snInfo& a);

/**
 * Class generated from <tt>src/node/application/nodeSensor/SnToIotPacket.msg:32</tt> by nedtool.
 * <pre>
 * packet SnToIotPacket extends ApplicationPacket
 * {
 *     snInfo extraData;
 * }
 * </pre>
 */
class SnToIotPacket : public ::ApplicationPacket
{
  protected:
    snInfo extraData_var;

  private:
    void copy(const SnToIotPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SnToIotPacket&);

  public:
    SnToIotPacket(const char *name=NULL, int kind=0);
    SnToIotPacket(const SnToIotPacket& other);
    virtual ~SnToIotPacket();
    SnToIotPacket& operator=(const SnToIotPacket& other);
    virtual SnToIotPacket *dup() const {return new SnToIotPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual snInfo& getExtraData();
    virtual const snInfo& getExtraData() const {return const_cast<SnToIotPacket*>(this)->getExtraData();}
    virtual void setExtraData(const snInfo& extraData);
};

inline void doPacking(cCommBuffer *b, SnToIotPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SnToIotPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SNTOIOTPACKET_M_H_

